DRIVER_CLASS_NAME: "org.sqlite.JDBC"
JDBC_URL: "jdbc:sqlite:dev.db"
DB_USERNAME: "admin"
DB_PASSWORD: "admin"
MAX_POOL_SIZE: 10
AUTO_COMMIT: true
IS_READ_ONLY: false
TRANSACTION_ISOLATION: "TRANSACTION_SERIALIZABLE"

JWT_ISSUER: "SHADE-SOFTWARE"
JWT_EXPIRATION: 86400000
JWT_SECRET: d56d9e98eddf914b95d670cd4991afda46f943fb7d28fa64d6170fb45cf1ad11771ca8f7104b824809bccbfc834a39170a0fe14397f0bde8cbdb9e54cc3344f2
