database:
  driverClassName: ${DRIVER_CLASS_NAME}
  jdbcUrl: ${JDBC_URL}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  maximumPoolSize: ${MAX_POOL_SIZE}
  isAutoCommit: ${AUTO_COMMIT}
  isReadOnly: ${IS_READ_ONLY}
  transactionIsolation: ${TRANSACTION_ISOLATION}

jwt:
  issuer: ${JWT_ISSUER}
  expiration: ${JWT_EXPIRATION}
  secret: ${JWT_SECRET}
