// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecVault.Data;

#nullable disable

namespace SecVault.Migrations
{
    [DbContext(typeof(PasswordContext))]
    [Migration("20240208135355_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("SecVault.MVVM.Model.Password.Password", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.ComplexProperty<Dictionary<string, object>>("CardInfo", "SecVault.MVVM.Model.Password.Password.CardInfo#CardInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime?>("CardExpiryDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("card_expiry_date");

                            b1.Property<string>("CardNote")
                                .HasColumnType("TEXT")
                                .HasColumnName("card_notes");

                            b1.Property<string>("CardNumber")
                                .HasColumnType("TEXT")
                                .HasColumnName("card_number");

                            b1.Property<string>("Pin")
                                .HasColumnType("TEXT")
                                .HasColumnName("card_pin");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PasswordDate", "SecVault.MVVM.Model.Password.Password.PasswordDate#PasswordDate", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime?>("CreatedDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("creation_date");

                            b1.Property<DateTime?>("LastUpdatedDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("last_updated_date");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PasswordInfo", "SecVault.MVVM.Model.Password.Password.PasswordInfo#PasswordInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Email")
                                .HasColumnType("TEXT")
                                .HasColumnName("email");

                            b1.Property<string>("EncPassword")
                                .HasColumnType("TEXT")
                                .HasColumnName("encrypted_password");

                            b1.Property<bool>("IsFavourite")
                                .HasColumnType("INTEGER")
                                .HasColumnName("favourite");

                            b1.Property<string>("Username")
                                .HasColumnType("TEXT")
                                .HasColumnName("user_name");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PasswordTypeInfo", "SecVault.MVVM.Model.Password.Password.PasswordTypeInfo#PasswordTypeInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("IconUrl")
                                .HasColumnType("TEXT")
                                .HasColumnName("icon_url");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("name");

                            b1.Property<int>("PasswordCategoryType")
                                .HasColumnType("INTEGER")
                                .HasColumnName("password_type");

                            b1.Property<string>("WebsiteSiteUrl")
                                .HasColumnType("TEXT")
                                .HasColumnName("website_url");
                        });

                    b.HasKey("Id");

                    b.ToTable("password");
                });
#pragma warning restore 612, 618
        }
    }
}
